# Generated by Django 3.0.7 on 2022-09-20 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tvshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('autor', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=1024)),
                ('producer', models.CharField(max_length=512)),
                ('creators', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
                ('launch_date', models.DateField()),
                ('full_launch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow.Episode')),
                ('currently_watching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow.Tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='Sinopse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinopse_desc', models.CharField(default='null', max_length=1024)),
                ('sinopse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow.Tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeReleaseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('daytime', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_period', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='A', max_length=1)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow.Tvshow')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow.Tvshow'),
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_members', models.CharField(max_length=512)),
                ('related_tvshows', models.CharField(choices=[('T', 'Tvshow'), ('M', 'Movies')], max_length=1)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='tvshow.Tvshow')),
            ],
        ),
    ]
